[package]
name = "brainfuck"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ebnf-gen = { path = "ebnf-gen" }
anyhow = "1.0.57"
nightly-crimes = "1.0.2"
