pointer movement    = ">" | "<" ;
memory modification = "-" | "+" ;
IO instruction      = "." | "," ;
repeat              = "[" , block , "]" ;
instruction         = pointer movement | memory modification | IO instruction | repeat ;
block               = { instruction } ;